program: train.py 
method: bayes
metric:
  name: test/psnr
  goal: maximize
parameters:
  lr:
    distribution: uniform
    min: 0.00001
    max: 0.1
  batch_size:
    values: [4096, 8192, 16384]
  num_epochs:
    values: [20, 30, 40]
  scale:
    distribution: uniform
    min: 0.1
    max: 1.0
  distortion_loss_w:
    distribution: uniform
    min: 0.0
    max: 0.01
project: NeRFusion
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --use_sweep
  - --root_dir=data/scannet_official/scans/scene0000_00